version: '3.8'

services:

    reverse-proxy:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
          - 80:80
        networks:
            - default_network
        depends_on:
            - frontend
            - backend
    backend:
        image: backend2_5
        build: ../exercise2_3/backend/
        environment:
          - REDIS_HOST=redis-service
          - POSTGRES_HOST=db_exercise2_6
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DATABASE=postgres
        depends_on:
            - db
            - redis
        networks:
            - default_network
        container_name: backend_2_8

    frontend:
        image: frontend2_5
        build: ../exercise2_3/frontend/
        networks:
            - default_network
        container_name: frontend_2_8
        depends_on:
            - backend

    redis:
        image: redis
        restart: unless-stopped
        container_name: redis-service
        networks:
            - default_network
        volumes:
            - redisdb:/data
    
    db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - database:/var/lib/postgresql/data
        container_name: db_exercise2_6
        networks:
            - default_network

volumes:
    database:
    redisdb:
networks:
    default_network:
        name: default_network    

