version: '3.8'

services:
    
    frontend:
        image: frontend2_7
        build: ./ml-kurkkumopo-frontend
        ports:
            - 3000:3000
    
    backend:
        image: backend2_7
        build: ./ml-kurkkumopo-backend
        ports:
            - 5000:5000
        volumes:
            - model:/src/model
        depends_on:
            - training

    training:
        image: training2_7
        build: ./ml-kurkkumopo-training
        volumes:
            - model:/src/model
            - images:/src/imgs
            - data:/src/data

volumes:
    model:
    images:
    data: